Fix SyntaxError: Add missing closing bracket ] for EXCLUDE_KEYWORDS
Error on line 113:
  EXCLUDE_KEYWORDS = [
                     ^
  SyntaxError: '[' was never closed

Problem: EXCLUDE_KEYWORDS list (line 113-149) was missing closing bracket ]

Solution: Added ] on line 150 after "championship",

Now structure is:
  Line 113: EXCLUDE_KEYWORDS = [
  Lines 114-149: list items
  Line 150: ]  <- FIXED
  Line 151: (blank)
  Line 152: BAD_PHRASES = ...